name: "Setup Bun"

description: "Setup Bun"

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.0.1

    - name: Install dependencies
      run: bun install
      shell: bash
