name: Cypress

on: deployment_status

jobs:
  cypress:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: |
      github.event.deployment_status.state == 'success' && 
      github.event.deployment_status.environment == 'Preview'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Run cypress
        uses: cypress-io/github-action@v2
        with:
          install: false
          config: baseUrl=${{ github.event.deployment_status.target_url }}
