name: E2E test

on: deployment_status

jobs:
  e2e-test:
    if: |
      github.event.deployment_status.state == 'success' && 
      github.event.deployment_status.environment == 'Preview'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install playwright dependencies
        run: pnpm playwright install --with-deps
      - name: Run e2e test
        run: pnpm test:e2e
        env:
          PLAYWRIGHT_BASE_URL: ${{ github.event.deployment_status.target_url }}
      - name: Upload playwright report
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 14
