name: Lighthouse CI

on: deployment_status

jobs:
  lighthouse-ci:
    if: |
      github.event.deployment_status.state == 'success' && 
      github.event.deployment_status.environment == 'Preview'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run lhci collect
        run: npx --package @lhci/cli lhci collect --url ${{ github.event.deployment_status.target_url }}
      - name: Run lhci upload
        run: npx --package @lhci/cli lhci upload --githubAppToken ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
