name: Lighthouse CI

on: deployment_status

jobs:
  lighthouse-ci:
    if: |
      github.event.deployment_status.state == 'success' && 
      github.event.deployment_status.environment == 'Preview'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Run lhci collect
        run: bun --package @lhci/cli x lhci collect --url ${{ github.event.deployment_status.target_url }}

      - name: Run lhci upload
        run: bun --package @lhci/cli x lhci upload --githubAppToken ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
